astraly-labs/Pragma

contracts/oracle_controller/library.cairo
contracts/oracle_implementation/library.cairo

Excited to merge my first PR. Thank you Jonas!

Updated with_attr error messages with name of contract at front

---

.gitignore
contracts/oracle_controller/OracleController.cairo
contracts/oracle_controller/library.cairo

This PR adds a namespace to the oracle controller.  I found this blog useful in explaining how and why this is done:
https://medium.com/coinmonks/storage-variable-clashing-in-starknet-ce5f28e60886
I also added a couple small changes to the .gitignore because I am setting up a virtual environment.  I put this change inside this branch out of convenience.

add namespace to oracle controller

---

contracts/admin/Admin.cairo
contracts/admin/library.cairo
contracts/compute_engines/yield_curve/YieldCurve.cairo
contracts/entry/library.cairo
contracts/oracle_controller/OracleController.cairo
contracts/oracle_implementation/library.cairo
contracts/publisher_registry/PublisherRegistry.cairo

This uses namespaces for a few cairo libraries, which makes function names more legible.

add namespaces

---

contracts/oracle_controller/IEmpiricOracle.cairo
contracts/oracle_controller/IOracleController.cairo

Must have slipped through last review.

Fixed Aggregation Modes comment

---

empiric-package/empiric/admin/client.py
empiric-package/empiric/core/__init__.py
empiric-package/empiric/core/base_client.py
empiric-package/empiric/core/client.py
empiric-package/empiric/core/config.py
empiric-package/empiric/core/logger.py
empiric-package/empiric/core/utils.py
empiric-package/empiric/publisher/client.py
empiric-package/empiric/publisher/fetch/bitstamp.py
empiric-package/empiric/publisher/fetch/cex.py
empiric-package/empiric/publisher/fetch/coinbase.py
empiric-package/empiric/publisher/fetch/coingecko.py
empiric-package/empiric/publisher/fetch/cryptowatch.py
empiric-package/empiric/publisher/fetch/ftx.py
empiric-package/empiric/publisher/fetch/gemini.py
empiric-package/empiric/publisher/fetch/thegraph.py
publisher/monitor/balance/monitor-balance.py
publisher/monitor/price/monitor-price.py
publisher/sample-publisher/all/fetch-and-publish.py
publisher/utils/initialize_yield_curve.py
publisher/utils/yield_curve_set_oracle_controller.py
sample_client.py
tests/test_compute_engines/yield_curve.py

this adds the logger to all packages and refactors how it's set up a little bit.  This merges into the config_refactor branch before we bump the version.

add logger

---

empiric-package/empiric/core/client.py
empiric-package/empiric/core/config.py
empiric-package/empiric/core/entry.py
empiric-package/empiric/core/types.py
empiric-package/empiric/publisher/client.py
empiric-package/empiric/publisher/fetch/bitstamp.py
empiric-package/empiric/publisher/fetch/cex.py
empiric-package/empiric/publisher/fetch/coinbase.py
empiric-package/empiric/publisher/fetch/coingecko.py
empiric-package/empiric/publisher/fetch/cryptowatch.py
empiric-package/empiric/publisher/fetch/ftx.py
empiric-package/empiric/publisher/fetch/gemini.py
empiric-package/empiric/publisher/fetch/thegraph.py
publisher/monitor/price/monitor-price.py
tests/test_compute_engines/test_yield_curve.py
tests/test_oracle_controller.py
tests/test_oracle_implementation.py
tests/utils.py

Created `Entry` class that replaces namedtuple. Comes with extra steps to construct entry in `get_entries` in `core/client.py`.

Created Entry class

---

.github/workflows/integration_net_test.yaml
empiric-package/empiric/core/utils.py
publisher/sample-publisher/all/fetch-and-publish.py
publisher/sample-publisher/coinbase/fetch-and-publish.py
publisher/sample-publisher/integration/fetch-and-publish.py
sample_client.py

Fixes small error in the GitHub action. 
If you look at the [action history](https://github.com/42labs/Empiric/actions/runs/2919729801) it says the run succeeded even though publishing failed. I'm not sure what to do about that.

Fix integration net action

---

.github/workflows/push_empiric_publisher.yaml

Had previously failed: https://github.com/42labs/Empiric/runs/8024056436?check_suite_focus=true

Pass if no release of new package

---

contracts/lib/time_series/utils.cairo

A simpler implementation for are_equal

simpler implementation are_equal

---

contracts/build/Oracle_abi.json
contracts/build/Randomness_abi.json
contracts/src/compute_engines/rebase_denomination/RebaseDenomination.cairo
contracts/src/compute_engines/yield_curve/YieldCurve.cairo
contracts/src/oracle/IOracle.cairo
contracts/src/oracle/Oracle.cairo
contracts/src/oracle/library.cairo
contracts/tests/test_compute_engines/test_summary_stats.cairo
docs/quickstart.md
empiric-package/.bumpversion.cfg
empiric-package/empiric/cli/contracts/oracle.py
empiric-package/empiric/core/abis/oracle.py
empiric-package/empiric/core/abis/publisher_registry.py
empiric-package/empiric/core/mixins/oracle.py
empiric-package/setup.cfg
empiric-ui/src/abi/OracleController.json
sample_client.py
stagecoach/integration_tests/price/Dockerfile
stagecoach/integration_tests/price/app.py
stagecoach/integration_tests/publish-all/Dockerfile
stagecoach/jobs/publishers/examples/publish_all.py
stagecoach/monitors/price/app.py
tests/test_compute_engines/test_summary_stats.py
tests/test_compute_engines/test_yield_curve.py
tests/test_compute_engines/yield_curve.py
tests/test_oracle.py
tests/utils.py

this makes it so when you get entries, if they are all stale it will get the latest entries within the TIMESTAMP_BUFFER of the latest entry

filter on latest timestamp

---

empiric-package/.bumpversion.cfg
empiric-package/setup.cfg

this exposes the `cli` package

expose cli package

---

contracts/src/compute_engines/summary_stats/library.cairo
contracts/src/oracle/IOracle.cairo
contracts/src/oracle/Oracle.cairo
contracts/src/oracle/library.cairo
contracts/tests/test_compute_engines/test_summary_stats.cairo

adds a method to get the last checkpoint before a time for a specific key and timestamp.  Returns the checkpoint and its index.

add checkpoint function and test

---

contracts/build/Oracle_abi.json
contracts/src/compute_engines/summary_stats/SummaryStats.cairo
contracts/src/compute_engines/summary_stats/library.cairo
contracts/src/oracle/library.cairo
contracts/tests/test_compute_engines/test_summary_stats.cairo
empiric-package/empiric/cli/contracts/oracle.py
empiric-package/empiric/cli/contracts/summary_stats.py
empiric-package/empiric/core/abis/oracle.py
tests/test_compute_engines/test_summary_stats.py

This updated the oracle abi and annualizes the volatility in summary stats

Update oracle abi

---

contracts/build/Oracle_abi.json
contracts/src/compute_engines/summary_stats/SummaryStats.cairo
contracts/src/compute_engines/summary_stats/library.cairo
contracts/src/oracle/library.cairo
contracts/tests/test_compute_engines/test_summary_stats.cairo
empiric-package/.bumpversion.cfg
empiric-package/empiric/cli/contracts/oracle.py
empiric-package/empiric/cli/contracts/summary_stats.py
empiric-package/empiric/core/abis/oracle.py
empiric-package/empiric/core/mixins/oracle.py
stagecoach/jobs/publishers/publish-all/app.py
tests/test_compute_engines/test_summary_stats.py

filter entries before serializing them

filter entries before paginating

---

analytics/notebooks/Empiric Performance Analysis August 11.ipynb
analytics/notebooks/Empiric Performance Analysis.ipynb
empiric-package/.bumpversion.cfg
empiric-package/empiric/cli/net.py
empiric-package/empiric/core/client.py
empiric-package/empiric/core/contract.py
empiric-package/setup.cfg
requirements.txt

Cleanup Code & Migrate to StarknetPy 0.13.0 ⬆️✨

---

contracts/starknet/lib/time_series/convert.cairo
contracts/starknet/src/entry/library.cairo
contracts/starknet/src/entry/structs.cairo
contracts/starknet/src/oracle/IEmpiricOracle.cairo
contracts/starknet/src/oracle/IOracle.cairo
contracts/starknet/src/oracle/Oracle.cairo
contracts/starknet/src/oracle/library.cairo
contracts/starknet/tests/test_oracle.cairo
protostar.toml
tests/test_oracle.py

Implementing new functionalities to the Oracle: 
- Retreive futures and generic decimals 
- Retreive pair and currency informations

feat:Adding new functions

---

pragma-ui/package.json
pragma-ui/public/sitemap.xml
pragma-ui/src/components/optimistic/Assessment.tsx
pragma-ui/src/components/optimistic/AssessmentPopup.tsx
pragma-ui/src/pages/optimistic.tsx
pragma-ui/src/utils/index.ts
pragma-ui/yarn.lock

## Fixes 
- Time based on timezone
- Accurate loading bar
- Currency logo display

fix: Time and Currency display

---

pragma-ui/src/app/assets/_components/asset-perf.tsx
pragma-ui/src/app/assets/_helpers/getTokens.ts
pragma-ui/src/pages/api/fetchData.ts

- Adds all initial assets following our documentation

feat: add all remaining assets

---

pragma-ui/src/app/assets/_components/asset-row.tsx
pragma-ui/src/app/assets/_helpers/startStreaming.ts
pragma-ui/src/components/Navigation/NavHeader.tsx
pragma-ui/src/pages/index.tsx
pragma-ui/src/providers/data.tsx

- Remove Pragma V2 and Optimistic links from the navbar
- Enable prefetching
- Fix streams

fix: remove non existing pages links from header

---

pragma-ui/src/app/asset/[ticker]/_components/asset-chart.tsx
pragma-ui/src/app/asset/[ticker]/_helpers/getAsset.ts
pragma-ui/src/app/asset/[ticker]/_helpers/startStreaming.ts
pragma-ui/src/app/asset/[ticker]/_helpers/useEventSourceQuery.ts
pragma-ui/src/app/assets/_components/asset-row.tsx

- https://github.com/astraly-labs/Pragma/issues/453
- https://github.com/astraly-labs/Pragma/issues/443

styling: fix ui on /assets and stream

---

pragma-ui/src/app/(dashboard)/asset/[ticker]/_components/asset-chart.tsx
pragma-ui/src/app/(dashboard)/asset/[ticker]/_components/asset-header.tsx
pragma-ui/src/app/(dashboard)/asset/[ticker]/page.tsx
pragma-ui/src/components/ui/chart.tsx

https://github.com/user-attachments/assets/7ee98d7c-9341-4c1e-8376-dd9206380cf0

feat: new custom chart
